// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelefonRehberi.Data;

#nullable disable

namespace TelefonRehberi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TelefonRehberi.Models.Kisi", b =>
                {
                    b.Property<int>("KisiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KisiId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("KisiId");

                    b.HasIndex("TelefonNumarasi")
                        .IsUnique();

                    b.HasIndex("Ad", "Soyad")
                        .IsUnique();

                    b.ToTable("Kisiler");
                });
#pragma warning restore 612, 618
        }
    }
}
